FROM python:3.10


WORKDIR /app/
#ADD ./Codes/djangoProject ./
#RUN pip install -r ./requirements.txt
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY . /app
RUN pip install --upgrade pip


ENTRYPOINT ["/bin/sh", "-c" , "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 tech_news.wsgi"]