# Generated by Django 5.0.8 on 2024-08-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='news.tag'),
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
